#!/usr/bin/env python3
# -*- coding: utf-8 -*-
#  ---------------------------------------------------------------------
#
#  _____    _      _              _         _____ _____
# | ____|__| | ___| |_      _____(_)___ ___|  ___| ____|
# |  _| / _` |/ _ \ \ \ /\ / / _ \ / __/ __| |_  |  _|
# | |__| (_| |  __/ |\ V  V /  __/ \__ \__ \  _| | |___
# |_____\__,_|\___|_| \_/\_/ \___|_|___/___/_|   |_____|
#
#
#  Unit of Strength of Materials and Structural Analysis
#  University of Innsbruck,
#  2017 - today
#
#  Matthias Neuner matthias.neuner@uibk.ac.at
#
#  This file is part of EdelweissFE.
#
#  This library is free software; you can redistribute it and/or
#  modify it under the terms of the GNU Lesser General Public
#  License as published by the Free Software Foundation; either
#  version 2.1 of the License, or (at your option) any later version.
#
#  The full text of the license can be found in the file LICENSE.md at
#  the top level directory of EdelweissFE.
#  ---------------------------------------------------------------------
"""
Created on Wed Jun 14 21:40:55 2017

@author: Matthias Neuner
"""

import argparse
import os
import sys
from timeit import default_timer as timer

import matplotlib
import numpy as np
from rich import print as richPrint

from edelweissfe.domaindecomposition.mpienvironment import (
    isRootProcess,
    numberOfProcesses,
)
from edelweissfe.drivers.inputfiledrivensimulation import finiteElementSimulation
from edelweissfe.utils.inputfileparser import parseInputFile

matplotlib.use("Agg")


def report(*args, **kwargs):
    """Print a line of the test report, on the root process only.

    Under an MPI launcher every process runs every test and reaches the same verdict, so one process
    reports it.

    Parameters
    ----------
    *args
        What to print, as for ``rich.print``.
    **kwargs
        Keyword arguments of ``rich.print``, e.g. ``end``.
    """

    if isRootProcess():
        richPrint(*args, **kwargs)


def main():
    parser = argparse.ArgumentParser(description="validation script for FE analyses")
    parser.add_argument("testdirectory", help="The directory containing the testfiles")
    parser.add_argument(
        "--create",
        dest="create",
        action="store_true",
        help="create reference solutions",
    )
    parser.add_argument(
        "--tests",
        help="comma-separated list (without whitespace inbetween) with names of analyzed test files, "
        "e.g. MeshPlot,NodeForces, or simply type all. The names are case-sensitive.",
        type=str,
        default="all",
    )
    args = parser.parse_args()

    testfile = "test.inp"
    referenceSolutionFile = "U.ref"
    tests = [item for item in args.tests.split(",")]

    testfilesDir = os.path.abspath(args.testdirectory)

    processes = numberOfProcesses()
    report(
        "[blue]{} MPI process{}, testing {}[/]".format(processes, "" if processes == 1 else "es", args.testdirectory)
    )
    os.chdir(testfilesDir)
    testsDirs = next(os.walk("."))[1]
    testsDirs = sorted(testsDirs, key=str.casefold)

    if "all" not in tests:
        # Filter, preserving the sorted order established above. Going through a set discards it,
        # and the order is load-bearing: a test case may consume a file another one produces (a
        # *include of a generated mesh, or a restart checkpoint), so a --tests run could otherwise
        # execute the consumer first and compare against a stale artefact from an earlier run.
        requested = set(tests)
        testsDirs = [directory for directory in testsDirs if directory in requested]

    failedTests = 0
    skippedTests = 0
    directoriesWithoutTest = []

    for directory in testsDirs:
        os.chdir(os.path.join(testfilesDir, directory))

        # A directory without a test.inp is not a test; it is listed at the end so that a deck
        # saved under another name does not silently drop out of the suite.
        if not os.path.exists(testfile):
            directoriesWithoutTest.append(directory)
            continue

        try:
            inputFile = parseInputFile(testfile)
            report("Test {:50}".format(directory), end="\r")
        except ValueError as e:
            report("Test {:50} [red]FAILED DURING PARSING[/]: ".format(directory) + str(e))
            failedTests += 1
            continue
        except (NotImplementedError, ModuleNotFoundError) as e:
            # e.g. an unbuilt optional Cython extension, or a *include of a file generated by
            # another (itself skipped) test - report as a skip rather than crashing the whole run.
            report("Test {:50} [grey]SKIPPED[/]: ".format(directory) + str(e))
            skippedTests += 1
            continue
        except Exception as e:
            report("Test {:50} [red]FAILED DURING PARSING[/]: ".format(directory) + str(e))
            failedTests += 1
            continue

        try:
            tic = timer()
            model, fieldOutputController = finiteElementSimulation(inputFile, verbose=False, suppressPlots=True)
            toc = timer()

            u = [f["U"].flatten() for f in model.nodeFields.values()]
            sv = [v.value for v in model.scalarVariables.values()]

            U = np.hstack(u + sv).flatten()

            if not args.create:
                UReference = np.atleast_1d(np.loadtxt(referenceSolutionFile))

                if U.shape != UReference.shape:
                    report(
                        "Test {:50} [red]FAILED[/]: {} values, but the reference has {}".format(
                            directory, U.size, UReference.size
                        )
                    )
                    failedTests += 1
                elif np.max(np.abs(U - UReference)) < 1e-6:
                    report("Test {:50} [green]PASSED[/] [{:2.1f}]".format(directory, toc - tic))
                else:
                    report("Test {:50} [red]FAILED[/]".format(directory))
                    failedTests += 1
                os.chdir("..")
            else:
                report("")
                if isRootProcess():
                    np.savetxt(referenceSolutionFile, U)

        except (NotImplementedError, ModuleNotFoundError) as e:
            report("Test {:50} [grey]SKIPPED[/]: ".format(directory) + str(e))
            skippedTests += 1
            continue

        except Exception as e:
            report("Test {:50} [red]FAILED[/]: ".format(directory) + str(e))
            failedTests += 1
            continue

    if directoriesWithoutTest:
        report("[grey]Directories without a {}: {}[/]".format(testfile, ", ".join(directoriesWithoutTest)))
    report("[blue]Tests skipped: {:3}[/]".format(skippedTests))
    report("[blue]Tests failed: {:3}[/]".format(failedTests))
    if failedTests > 0:
        sys.exit(1)


if __name__ == "__main__":
    main()
