#!/usr/bin/env python3
"""P0 of PLAN_TOPOLOGY_PIPELINE.md: what does one topology round actually cost, and does that cost
scale with the *change* or with the *whole mesh*?

The question matters because `b0eb74f` bought its 2.04x replay speedup by collapsing 54
per-occasion materialisations into one -- i.e. by making the replay unfaithful. Faithful replay
(P2) hands that speedup back, so it has to be re-earned by making the per-round work incremental
instead. Which work, and how much, is what this measures.

Method: refine a FIXED number of elements (one, chosen by an elementSet marker) in meshes of
growing size. Any stage whose cost grows with the mesh is doing whole-mesh work for a local change
-- that is the incrementality opportunity. Any stage that stays flat is already proportional to the
change and can be left alone.

Run on xeon (see PLAN §0.2 -- idle machine, and never on the notebook):

    python3 profile_amr_round.py 4 8 12
"""

import re
import subprocess
import sys
from pathlib import Path

TEMPLATE = """** Generated by profile_amr_round.py -- P0 scaling probe. One element is refined regardless of
** mesh size, so any stage that grows with nX is doing whole-mesh work for a local change.
*material, name=linearelastic, id=mat
18000, 0.0

*section, name=sec, material=mat, type=solid
all

*modelGenerator, generator=boxGen, name=box
nX      ={n}
nY      ={n}
nZ      ={n}
x0      =0
y0      =0
z0      =0
lX      =1
lY      =1
lZ      =1
elType  =C3D20

*elSet, elSet=refineMe
1

*modelModifier, type=hAdaptivity, name=amr
>>marker, type=elementSet, elSet=refineMe, initialOnly=True
maxLevel=1

*job, name=amrprofile, domain=3d
*solver, solver=NIST, name=S
*fieldOutput
>>perNode, elSet=all, field=displacement, result=U, name=U

*step, solver=S
maxInc=1.0, minInc=1e-4, maxNumInc=1, maxIter=25,
>>dirichlet, name=bottom, nSet=box_bottom, field=displacement, 1=0.0, 2=0.0, 3=0.0
>>dirichlet, name=top, nSet=box_top, field=displacement, 2=0.001
"""

# The stages this is about: everything below is per-round work whose scaling we want to classify.
STAGES = [
    "topology update",
    "hanging: whole-mesh index build",
    "hanging: interface-shell scan",
    "elements & state transfer",
    "sets & fields sync",
    "fields resize & restore",
    "relink field variables",
    "notify observers",
    "refresh mesh dependents",
]


def runOne(n: int, workdir: Path) -> dict[str, float]:
    case = workdir / "case_{:}".format(n)
    case.mkdir(parents=True, exist_ok=True)
    (case / "test.inp").write_text(TEMPLATE.format(n=n))

    out = subprocess.run(["edelweissfe", "test.inp"], cwd=case, capture_output=True, text=True, check=False).stdout

    timings = {}
    for stage in STAGES:
        # the performancetiming table prints "| <stage> | <value> s |", wrapped to a fixed width
        match = re.search(re.escape(stage) + r"\s*\|\s*([0-9.eE+-]+)\s*s", out)
        if match:
            timings[stage] = float(match.group(1))
    timings["_elements"] = float(len(re.findall(r"^", out)))  # placeholder, replaced below
    match = re.search(r"elements:\s*(\d+)", out)
    if match:
        timings["_elements"] = float(match.group(1))
    return timings


def main():
    sizes = [int(a) for a in sys.argv[1:]] or [4, 8, 12]
    workdir = Path(__file__).parent / "_runs"
    results = {n: runOne(n, workdir) for n in sizes}

    print("\n{:38} {:}".format("stage [s]", "  ".join("nX={:<10}".format(n) for n in sizes)))
    print("-" * (38 + 14 * len(sizes)))
    print("{:38} {:}".format("elements", "  ".join("{:<12.0f}".format(results[n].get("_elements", 0)) for n in sizes)))
    for stage in STAGES:
        row = "  ".join("{:<12.4f}".format(results[n].get(stage, float("nan"))) for n in sizes)
        print("{:38} {:}".format(stage, row))

    print(
        "\nA stage growing roughly with the element count is doing whole-mesh work for a one-element\n"
        "refinement -- that is where incrementality pays (PLAN_TOPOLOGY_PIPELINE.md P6). A flat stage\n"
        "is already proportional to the change."
    )


if __name__ == "__main__":
    main()
